language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash-completion
  - echo 'source /etc/bash_completion' | sudo tee /etc/bash.bashrc
script: python ./test.py
